on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          token: ${{ secrets.JOBYEONGWOOK_GIT }}
          pull-request-header: ':robot: Changelog'
          changelog-types: >
            [
              { "type": "build", "section": "ğŸ“¦ Build System", "hidden": false },
              { "type": "ci", "section": "ğŸ‘· Continuous Integration", "hidden": false },
              { "type": "chore", "section": "ğŸ”§ Miscellaneous Chores", "hidden": false },
              { "type": "docs", "section": "ğŸ“š Documentation", "hidden": false },
              { "type": "feat", "section": "âœ¨ Features", "hidden": false },
              { "type": "fix", "section": "ğŸ› Bug Fixes", "hidden": false },
              { "type": "perf", "section": "âš¡ Performance Improvements", "hidden": false },
              { "type": "revert", "section": "â– Reverts", "hidden": false },
              { "type": "refactor", "section": "â™»ï¸ Code Refactoring", "hidden": false },
              { "type": "style", "section": "ğŸ¨ Styles", "hidden": false },
              { "type": "test", "section": "ğŸš¨ Tests", "hidden": false },
              { "type": "design", "section": "ğŸ– Designs", "hidden": false }
            ]